baseurl = "https://movid-coes.netlify.app/"
title = "MOVID-IMPACT-C"
theme = "hugo-universal-theme"
languageCode = "es-cl"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "es"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Inicio"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier = "app"
    name = "Descargar"
    url  = "/descargar/"
    weight = 2

[[menu.main]]
    identifier = "doc"
    name = "Documentación"
    url  = "/doc/"
    weight = 3

[[menu.main]]
    identifier = "contact"
    name = "Contacto"
    url  = "/contact/"
    weight = 4

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/CoV-IMPACT-C/"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Email"
    url = "mailto:encuestacovid@uchile.cl"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "MOVID-19"
    defaultKeywords = ["covid", "movid", "pandemia", "datos"]
    mainSections = ["blog"]
    defaultDescription = "Sitio desarrollado por valentinaandrade por template devcows usando hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "f/xeqpkdpl"
    contact_form_ajax = false

    about_us = "<p>Coronavirus Impact Monitor:Policiy, Access, Control and Transectorial Consequences</p>"
    copyright = "Copyright (c) 2020 - 2021, ANID-COVID 960; todos los derechos reservados."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p class="text-uppercase"><strong>MOVID</strong>
        <br>Universidad de Chile
        <br>Santiago-RM
        <br>Chile
        <br>
      </p>
      """

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contáctenos en encuestacovid@uchile.cl</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = false

[params.carousel]
    enable = false
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.test]
    enable = true
    title = "MOVID-IMPACT-C"
    subtitle = "MOVID-IMPACT-C es una encuesta representativa a nivel nacional realizada por el equipo CoV-IMPACT-C"


[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Módulos"
    subtitle = ""

[params.see_more]
    enable = true
    icon = "fas fa-chart-line"
    title = "MOVID-IMPACT-C"
    subtitle = ""
    link_url = "/descargar base de datos/"
    link_text = "Descargar base de datos"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = ""
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "Noticias"
    subtitle = "En el siguiente apartado se pueden ver las noticias que han aparecido sobre el Observatorio de Cohesión Social"
